"""foreign key added to the questionbank hehhehe

Revision ID: 03c69ce041e3
Revises: afb3b588a5e4
Create Date: 2024-06-02 20:10:23.956195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03c69ce041e3'
down_revision: Union[str, None] = 'afb3b588a5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionbank', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questionbank', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questionbank', type_='foreignkey')
    op.drop_column('questionbank', 'topic_id')
    # ### end Alembic commands ###
