# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: like_unlike_post.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'like_unlike_post.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16like_unlike_post.proto\"Y\n\nLikePosted\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\x05\x12\x10\n\x08liked_by\x18\x03 \x01(\t\x12\x14\n\x0cliked_status\x18\x04 \x01(\x08\"G\n\x0cUnlikePosted\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\x05\x12\x12\n\nunliked_by\x18\x03 \x01(\t\"c\n\x0c\x45ventWrapper\x12\"\n\x0blike_posted\x18\x01 \x01(\x0b\x32\x0b.LikePostedH\x00\x12&\n\runlike_posted\x18\x02 \x01(\x0b\x32\r.UnlikePostedH\x00\x42\x07\n\x05\x65ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'like_unlike_post_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LIKEPOSTED']._serialized_start=26
  _globals['_LIKEPOSTED']._serialized_end=115
  _globals['_UNLIKEPOSTED']._serialized_start=117
  _globals['_UNLIKEPOSTED']._serialized_end=188
  _globals['_EVENTWRAPPER']._serialized_start=190
  _globals['_EVENTWRAPPER']._serialized_end=289
# @@protoc_insertion_point(module_scope)
