# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coment_wraper.proto
# Protobuf Python Version: 5.28.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    0,
    '',
    'coment_wraper.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63oment_wraper.proto\"p\n\x0c\x41\x64\x64\x65\x64\x43omment\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\x05\x12\x12\n\ncomment_by\x18\x03 \x01(\t\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x16\n\x0e\x63omment_status\x18\x05 \x01(\x08\"4\n\rDeletedComent\x12\x12\n\nevent_type\x18\x01 \x01(\t\x12\x0f\n\x07post_id\x18\x02 \x01(\x05\"o\n\x12\x45ventWrapperComent\x12&\n\rcoment_posted\x18\x01 \x01(\x0b\x32\r.AddedCommentH\x00\x12(\n\x0e\x64\x65leted_coment\x18\x02 \x01(\x0b\x32\x0e.DeletedComentH\x00\x42\x07\n\x05\x65ventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coment_wraper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDEDCOMMENT']._serialized_start=23
  _globals['_ADDEDCOMMENT']._serialized_end=135
  _globals['_DELETEDCOMENT']._serialized_start=137
  _globals['_DELETEDCOMENT']._serialized_end=189
  _globals['_EVENTWRAPPERCOMENT']._serialized_start=191
  _globals['_EVENTWRAPPERCOMENT']._serialized_end=302
# @@protoc_insertion_point(module_scope)
