"""make changes to table 

Revision ID: e7523fe4e2cd
Revises: 
Create Date: 2024-09-12 12:15:07.006931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7523fe4e2cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weloe')
    op.drop_table('test')
    op.add_column('post', sa.Column('likecount', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('comment_count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('share', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'share')
    op.drop_column('post', 'comment_count')
    op.drop_column('post', 'likecount')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.create_table('weloe',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('pathIs', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='weloe_pkey')
    )
    # ### end Alembic commands ###
