"""Create a baseline migrations

Revision ID: 60953ad5f966
Revises: 
Create Date: 2024-12-03 06:01:40.856658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60953ad5f966'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('university', sa.Column('followers_count', sa.Integer(), nullable=True))
    op.alter_column('university', 'website',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('university', 'website',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('university', 'followers_count')
    # ### end Alembic commands ###
